server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rajesh606081/app-config.git
          username: rajesh606081
          password: Aug12345
